---
- name: ensure ntpd is started
  service:
    name: ntp
    state: started
    enabled: yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  service:
    name: ntpd
    state: started
    enabled: yes
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
